import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import MenuStateProvider from "@/context/MenuStateProvider";
import Header from "@/components/Header";
import Sidebar from "@/components/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Trello Dashboard Clone",
  description: "Generated by APIXcel Team - RiaJul Pro",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <MenuStateProvider>
          <article className="flex flex-col justify-betweenl h-screen  bg-[#1d2125]">
            <Header />
            <section className="h-full w-full flex justify-center items-start">
              <Sidebar />
              <main className="flex-1 w-full h-full">{children}</main>
            </section>
          </article>
        </MenuStateProvider>
      </body>
    </html>
  );
}
